### ISSUE TITLE
Improving Routing🤓

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#103]
Currently, as soon as you make the pdf and then click the back button t doesn't redirect you to the home page.
this can be solved in either of the two approaches.
1. As soon as the pdf is made instead of showing the pdf there redirect to the home page.
2. **Preferred Method**: As soon as the back button is pressed on the pdf it should open the Home Page.

**Comment by Saransh-cpp** [comment]
I would like to take up this issue. I was exploring this issue and I found that after pressing the back button, the blank PDFViewerScaffold is shown, so my main idea for this issue is to create a timer of 0 seconds which pushes the home page automatically. Whenever the user presses the back button, the time is activated and it immediately performs pushReplacement() which leads the user to home.
