### ISSUE TITLE
Suggestion And Features in App ✨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#104]
Any Features you want to suggest in-app feel free to do so

**Comment by Saransh-cpp** [comment]
One of the main issue right now is the infinite stacking of screens, I created an issue on this too but soon realized that a simple pushReplacement won't work here. My suggestion would be to find something that overcomes this. Currently I am avoiding implementing a new or a big feature because of my internal examinations (I hope that is understandable) but here is a [good resource](https://github.com/orestesgaolin/navigator_20_example) I found on this. If no one works on it, I will implement this in the upcoming week!

**Comment by anushbhatia** [comment]
Sureee this is indeed needed in the application. Open up a issue for this 🤗.
