### ISSUE TITLE
Facing error on startup

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#176]
Screenshot:

![WhatsApp Image 2021-03-14 at 10 34 45](https://user-images.githubusercontent.com/29424616/111057929-03a2a280-84b1-11eb-9313-0c2e595f1b4d.jpeg)

**Comment by SapinderSingh** [comment]
I would like to work on this issue as a participant of GSSOC 21.

**Comment by Saransh-cpp** [comment]
@SapinderSingh thanks for pointing this out! I worked on this today because this issue was something that was breaking down the whole app and there wasn't any concrete info in the console as to what was causing this issue (and this issue only appears if you freshly install the app, after uninstalling it from your device). I have fixed this but I won't make a PR for the code, try exploring the repository for 1-2 days specifically the Hive boxes' areas, and check if you can find the fix. If not then feel free to ping me anywhere and I will guide you as to how to fix this so you can create a PR!:)

**Comment by SapinderSingh** [comment]
@Saransh-cpp Thanks :)

**Comment by anushbhatia** [comment]
Sure you can go through this and see if you could find the error in this place.
This issue is there in taking the system ui prefrences and that's y its giving that error.

**Comment by SapinderSingh** [comment]
Please assign this issue to me as I have found the bug and please label it with GSSOC 21

**Comment by arteevraina** [comment]
> @SapinderSingh thanks for pointing this out! I worked on this today because this issue was something that was breaking down the whole app and there wasn't any concrete info in the console as to what was causing this issue (and this issue only appears if you freshly install the app, after uninstalling it from your device). I have fixed this but I won't make a PR for the code, try exploring the repository for 1-2 days specifically the Hive boxes' areas, and check if you can find the fix. If not then feel free to ping me anywhere and I will guide you as to how to fix this so you can create a PR!:)

This is the real spirit of Open Source :heart:
