### ISSUE TITLE
Improve Cards in Home page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#194]
In light mode, the colours used here are grey replacing them with white and adding a box-shadow on it so that it looks like a card.
also making icons grey in light mode rather than black so that it doesn't here.
![Screenshot_20210317_012831](https://user-images.githubusercontent.com/40017559/111372123-3c649680-86c0-11eb-9742-e69c10bf3d36.jpg)

**Comment by Neha62-lit** [comment]
@anushbhatia I would like to work on this issue as a part of GSSOC'21!!

**Comment by Saransh-cpp** [comment]
@Neha62-lit can you please make all the colors dynamic in another PR? so that they change according to the theme. Switching the app to dark mode messes up the PDF cards. 

## Screenshot
<img src="https://user-images.githubusercontent.com/74055102/111680304-179b2b00-8848-11eb-9139-cea7b5062ff3.png" height="500px"/>

Should we re-open this issue?

**Comment by abstrxtInfinity** [comment]
Assign this to me, I have fixed this. pr #222
