### ISSUE TITLE
Starrred Document Error

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#208]
If try to star a document in the home screen and unstar it from the starred document it doesn't remove the selected star to unselected one in home

https://user-images.githubusercontent.com/40017559/111680091-dd318e00-8847-11eb-8c43-fdf2f91a7b4d.mp4

**Comment by Saransh-cpp** [comment]
The problem here is that the home screen is lying below the starred documents screen, so when we go back the home screen doesn't build up rather the home screen lying below is shown. Going back to home screen (after un-starring the PDF) and then pressing the refresh button in the app bar makes the star icon "un-starred" (this confirms the first sentence). For such a situation we can maybe use streams but I am not so sure.

**Comment by anushbhatia** [comment]
Yep stream builder has to be used to get updated output from the previous screen to this.
