### ISSUE TITLE
Feature Request: Introduction of reordering pdf pages before finalizing to make the pdf.

### ISSUE THREAD

**Issue by adrishyantee** [smaranjitghose/DocLense#230]
The pdf pages are set as we select the image items but it would have been user-friendly if it had to reorder the pdf pages before actually making a pdf. This would provide more control to users to design the pdf in their way.

**Comment by adrishyantee** [comment]
Can someone help me with this? Would be of much help if I get ideas to implement this.

**Comment by Saransh-cpp** [comment]
> Can someone help me with this? Would be of much help if I get ideas to implement this.

Check out [this](https://pub.dev/packages/reorderables) package, it is in sync with the latest flutter updates. @anushbhatia should we go ahead with this?

**Comment by anushbhatia** [comment]
yep LGTM

**Comment by Saransh-cpp** [comment]
I will try to implement the feature as no one is working on this.

**Comment by Saransh-cpp** [comment]
Turns out, this is weirdly difficult to implement using the package above and all the rest packages and in-built widgets are made to reorder a ListView and not a GridView. One helpful package I found was [this](https://github.com/DevOrbiter/drag_and_drop_gridview) which has been updated to null safety on GitHub but they haven't updated the same on pub.dev (which they are planning to do). I will implement this as soon as the package gets the update.

**Comment by smaranjitghose** [comment]
> Turns out, this is weirdly difficult to implement using the package above and all the rest packages and in-built widgets are made to reorder a ListView and not a GridView. One helpful package I found was [this](https://github.com/DevOrbiter/drag_and_drop_gridview) which has been updated to null safety on GitHub but they haven't updated the same on pub.dev (which they are planning to do). I will implement this as soon as the package gets the update.

Cool!
