### ISSUE TITLE
Improving the style of displaying the pdf's in home page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#99]
Currently, there are represented just by a white card with its name on it we add multiple features to it.
Design and features of it are listed below check them and also you can implement each feature at a time.

**Comment by anushbhatia** [comment]
![Screenshot_20210211_113747_com adobe scan android](https://user-images.githubusercontent.com/40017559/107606957-c18e0300-6c5d-11eb-84c5-4e0eff570828.jpg)
![Screenshot_20210211_113752_com adobe scan android](https://user-images.githubusercontent.com/40017559/107606965-c81c7a80-6c5d-11eb-882b-3893a7708a97.jpg)

**Comment by Saransh-cpp** [comment]
@anushbhatia I was trying to work on this issue and this is what I got so far, should I open a PR for this? The share button works! but the delete button for now shows a dialogue box where pressing the delete button doesn't work.

![Screenshot_1613373817](https://user-images.githubusercontent.com/74055102/107916920-1ba80480-6f8d-11eb-921f-de8507980ef3.png)

@infiniteoverflow can you please help me out or carry out the deleting functioning of the PDF? I tried a lot but I am not well versed with the Hive box. Here are 2 of the lines (commented out) which work but they delete all the PDFs together giving an error on the screen that the index is invalid (because everything got deleted). Thank you!

![image](https://user-images.githubusercontent.com/74055102/107917229-9b35d380-6f8d-11eb-82a7-084dd357e1fc.png)

Error -

![image](https://user-images.githubusercontent.com/74055102/107917485-02538800-6f8e-11eb-8c0f-2b2183e27fbc.png)

**Comment by infiniteoverflow** [comment]
@Saransh-cpp You can use something like `pdfsBox.deleteAt(index)` , since we have used a listview builder , you can easily get the index of the item you are deleting. So with that u can delete that particular item.

For reference. : https://github.com/infiniteoverflow/Todo-App/blob/main/lib/main.dart
Check out the code that i have written to delete a tile.

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp You can use something like `pdfsBox.deleteAt(index)` , since we have used a listview builder , you can easily get the index of the item you are deleting. So with that u can delete that particular item.
> 
> For reference. : https://github.com/infiniteoverflow/Todo-App/blob/main/lib/main.dart
> Check out the code that i have written to delete a tile.

Thanks! I will try this and let you know if I face any issues!

**Comment by infiniteoverflow** [comment]
@Saransh-cpp Sure. Reach out to me via Discord, will clear any doubts if u have.

**Comment by subhangi2731** [comment]
can I work on this?

**Comment by anushbhatia** [comment]
would you add a small preview of the image on it?
